#!/usr/bin/env bash


export DOTFILES=$(dirname $0)

echo '
  __| | ___ | |_
 / _` |/ _ \| __|
| (_| | (_) | |_
 \__,_|\___/ \__|

'

export DOTFILES="${DOTFILES:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null && pwd)}"

echo -e "\n . <(cat $DOTFILES/config/bash/bashrc)" >> $HOME/.bashrc
echo -e '\n export PATH=$PATH:$HOME/.dotfiles/bin' > $DOTFILES/config/bash/.local

echo -e "Your dot setup is complete.\nRestart your shell and type 'dot -h' for help."
