#!/usr/bin/env bash

help() {
     grep '^#/' < "$0" | cut -c4-
}

validate_git_command() {
    if ! [ -x "$(command -v git)" ]; then
        echo "ERROR: git is not installed."
        exit 1
    fi
}

validate_curl_command() {
    if ! [ -x "$(command -v curl)" ]; then
        echo "ERROR: curl is not installed"
        exit 1
    fi
}

case "$1" in
    "-h"        ) help; exit 0 ;;
    "--help"    ) help; exit 0 ;;
esac
