#!/usr/bin/env bash

#/ install-all Install .X files configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/

. <(cat $DOTFILES_SCRIPTS/common/common)

for path in $(find "$DOTFILES_SCRIPTS" -name "install" -executable -type f)
do
    if [ -f $path ]; then
        $path
    fi
done
