#!/usr/bin/env bash

#/ Setup extra monitor
#/
#/ Flags:
#/   --help | -h Show help message
#/   --right Enable extra monitor on right side (Default)
#/   --left Enable extra monitor on left side
#/   --disconnect Disconnect current monitor
#/


help() {
     grep '^#/' < "$0" | cut -c4-
}

main() {
    monitors=$(xrandr --query | grep " connected" | cut -d" " -f1)

    for monitor in $monitors; do
        active_monitor=$(xrandr --listactivemonitors | tail +2 | grep -Eio $monitor | tail +2)

        if [ "$active_monitor" ]; then
            break
        fi

    done

    if [ ! "$active_monitor" ]; then
        echo "Can not found active monitors"
        exit 1
    fi

    if [ "$1" == "--left" ]; then
        side="--left-of"
    else
        side="--right-of"
    fi

    current_monitor=$(echo "$monitors" | grep "$active_monitor")
    monitor_to_active=$(echo "$monitors" | grep -v "$active_monitor")

    xrandr --output $monitor_to_active --auto $side $current_monitor

    if [ "$1" == "--disconnect" ] || [ "$2" == "--disconnect" ];then
        xrandr --output $current_monitor --off
        echo "Disconnect $current_monitor"
    fi

    i3-msg restart >> /dev/null

    echo "Connected $monitor_to_active"
}


main "$@"
