#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# define locale
export LC_ALL=en_US.UTF-8

# define X11 display
XDG_SESSION_TYPE=X11

# avoid duplicated bash history
export HISTCONTROL=ignoreboth:erasedups

# Default programs
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"
export TERM="xterm-256color"

# auto start X
if systemctl -q is-active graphical.target && [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx
fi
