#!/usr/bin/env bash

#/ Install neovim configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/

. <(cat $DOTFILES_SCRIPTS/common/common)

echo "INFO: installing neovim configuration"

validate_git_command
validate_curl_command

INIT_VIM=$HOME/.config/nvim/init.vim
COC_SETTINGS=$HOME/.config/nvim/coc-settings.json
COC_SNIPPETS=$HOME/.config/coc/ultisnips

# setup init.vim file
if [ ! -e "$INIT_VIM" ]; then
    mkdir -p $HOME/.config/nvim/

    if [ ! -f "~/.local/share/nvim/site/autoload/plug.vim"  ]; then
        curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi

    ln -s $DOTFILES/nvim/init.vim $INIT_VIM

    echo "WARNING: Reload your neovim and :PlugInstall to install plugins."
fi

# setup coc-settings.json
if [ ! -e "$COC_SETTINGS" ]; then
    ln -s $DOTFILES/nvim/coc-settings.json $COC_SETTINGS
fi

# setup coc snippets
if [ ! -d "$COC_SNIPPETS" ]; then
    mkdir -p $COC_SNIPPETS
fi
if [ ! -e "$COC_SNIPPETS"/go.snippets ]; then
    ln -s $DOTFILES/nvim/ultisnips/go.snippets $COC_SNIPPETS/go.snippets
fi

echo "INFO: your neovim configuration is complete :D"
