#!/usr/bin/env bash

#/ Setup neovim plugin manager configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/

set -e

help() {
     grep '^#/' < "$0" | cut -c4-
}

INIT_VIM=$HOME/.config/nvim/init.vim

echo "INFO: Setting neovim configuration"

if [ ! -e "$INIT_VIM" ]; then
    mkdir -p $HOME/.config/nvim/
fi

if [ ! -f "~/.local/share/nvim/site/autoload/plug.vim"  ]; then
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi


echo "INFO: your neovim configuration is complete :D"
