#!/usr/bin/env bash

#/ Uninstall neovim configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/

. <(cat $DOTFILES_SCRIPTS/common/common)

echo "INFO: uninstalling neovim configuration"

INIT_VIM=$HOME/.config/nvim/init.vim
COC_SETTINGS=$HOME/.config/nvim/coc-settings.json
COC_SNIPPETS=$HOME/.config/coc/ultisnips

if [ -L "$INIT_VIM" ]; then
    rm "$INIT_VIM"
fi


if [ -L "$COC_SETTINGS" ]; then
    rm "$COC_SETTINGS"
fi

if [ -d "$COC_SNIPPETS" ]; then
    rm -rf "$COC_SNIPPETS"
fi
