#!/usr/bin/bash

options="Shutdown\nReboot\nHibernate\nSuspend\nLock\nLogout\nCancel"
option=$(echo -e $options | dmenu -i -p "Menu")

case $option in
    "Shutdown" ) systemctl poweroff; exit 0;;
    "Reboot" ) systemctl reboot; exit 0;;
    "Hibernate" ) systemctl hibernate; exit 0;;
    "Suspend" ) systemctl suspend; exit 0;;
    "Lock" ) i3lock; exit 0;;
    "Logout" ) i3-msg exit; exit 0;;
    "" ) echo "Nothing to do"; exit 0;;
esac
