#!/usr/bin/env bash

#/ Install i3/i3blocks/rofi files configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/

. <(cat $DOTFILES_SCRIPTS/common/common)


setup_i3() {
    if [ ! -d $HOME/.config/i3 ]; then
        mkdir ~/.config/i3
    fi

    ln -s $DOTFILES/i3/config $HOME/.config/i3/config
    echo "INFO: i3 config installed"
}

setup_i3blocks() {
    git clone https://github.com/vivien/i3blocks-contrib ~/.config/i3blocks

    ln -s $DOTFILES/i3blocks/config $HOME/.config/i3blocks/config
    echo "INFO: i3blocks config installed"
}

setup_rofi() {
    ln -s $DOTFILES/rofi/config $HOME/.config/rofi/config
    echo "INFO: rofi config installed"
}

setup_i3
setup_i3blocks
setup_rofi

echo "INFO: your i3/i3blocks/rofi files configuration is complete :D"
