#!/usr/bin/env bash

#/ Install tmux configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/


. <(cat $DOTFILES_SCRIPTS/common/common)

echo "INFO: installing tmux configuration"

validate_git_command

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

echo "INFO: your .tmux.confg configuration is complete :D"
