#!/usr/bin/env bash

#/ Reload tmux sessions.
#/
#/ Flags:
#/   --help | -h Show help message
#/


help() {
     grep '^#/' < "$0" | cut -c4-
}

SESSION="tmp"

tmux new-session -s $SESSION -d

tmux send-key -t $SESSION  ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh Enter

# wait to reload sessions 
sleep 5

tmux kill-session -t $SESSION

echo -e "Sessions reloaded with successful\n"

echo -e "\nChoose one session to attached or empty to cancel:\n"

tmux ls

read -p "> " attached_session

if [ "$attached_session" ]; then
    tmux a -t $attached_session
fi
