#!/usr/bin/env bash

#/ Uninstall tmux configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/


. <(cat $DOTFILES_SCRIPTS/common/common)

echo "INFO: uninstalling tmux configuration"

TMUX_CONF=$HOME/.tmux.conf

if [ -L "$TMUX_CONF" ]; then
    rm "$TMUX_CONF"
fi
