#!/usr/bin/env bash

#/ Uninstall ~/.bash_profile file configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/

. <(cat $DOTFILES_SCRIPTS/common/common)

echo "INFO: uninstalling ~/.bash_profile configuration"

rm $HOME/.bash_profile
