#!/bin/bash -e

exists() {
  command -v "$1" >/dev/null 2>&1
}

install_packages() {
    if [ "$1" == "arch" ]; then
        echo "Installing Arch Linux packages..."
        sudo pacman -S - < ./scripts/base-packages.archlinux
    elif [ "$1" == "deb" ]; then
        echo "Installing Debian packages..."
        if !exists alacritty; then
            # Only add alacritty repository if alacritty is not installed.
            sudo add-apt-repository ppa:mmstick76/alacritty
        fi
        sudo apt install $(cat ./scripts/base-packages.debian)

        if ! exists brave-browser; then
            # Install Brave 
            sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
            sudo apt update
            sudo apt install brave-browser
        fi
    else
        echo "A distro base is required. Options are: arch, deb."
        exit 1
    fi

}

configure_base(){
    echo "Installing basic packages"
    install_packages $@
    echo "Finish with sucessful"
}


configure_base $@
