#!/bin/bash -e

exists() {
  command -v "$1" >/dev/null 2>&1
}

configure_editor() {
    PACKER=$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim

    if [ ! -f $PACKER ]; then
        echo "Installing packer"
        git clone --depth 1 https://github.com/wbthomason/packer.nvim\
            ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    fi

    if ! exists nvim; then
        echo "WARNING: neovim not installed"
    fi

    # Install neovim lsp
    if exists nvim; then
        echo "Installing Neovim tools"

        # Install python lsp
        pip install --user jedi-language-server
        python3 -m venv ~/.config/nvim/venv
        ~/.config/nvim/venv/bin/pip install -U pip
        ~/.config/nvim/venv/bin/pip install pynvim

        npm config set prefix '~/.npm'

        # Install lsp servers
        npm i -g bash-language-server dockerfile-language-server-nodejs vim-language-server \
            yaml-language-server typescript-language-server

        nvim +PackerSync +qall
    fi
}

install_tools() {
    if [ "$1" == "arch" ]; then
        echo "Installing Arch Linux development tools..."
        sudo pacman -S - < ./scripts/dev-packages.archlinux
    elif [ "$1" == "deb" ]; then
        echo "Installing Debian development tools..."
        sudo apt install $(cat ./scripts/dev-packages.debian)
    else
        echo "A distro base is required. Options are: arch, deb."
        exit 1
    fi
}


configure_dev() {
    install_tools $@
    configure_editor
}

configure_dev $@
