#!/bin/bash -e

configure_terminal() {
    ALACRITTY_PATH=~/.config/alacritty/
    ALACRITTY_FILE=$ALACRITTY_PATH/alacritty.yml
    if [ ! -d $ALACRITTY_PATH ]; then
        mkdir -p $ALACRITTY_PATH
    fi
    if [ ! -e $ALACRITTY_FILE ]; then
        echo "Configurating alacrity config file"
        ln -s $DOTFILES/alacritty/alacritty.yml $ALACRITTY_PATH/alacritty.yml
    fi
}

install_packages() {
    if [ "$1" == "arch" ]; then
        echo "Installing Arch Linux packages..."
        sudo pacman -S - < ./scripts/base-packages.archlinux
    elif [ "$1" == "deb" ]; then
        echo "Installing Debian packages..."
        sudo add-apt-repository ppa:mmstick76/alacritty
        sudo apt install $(cat ./scripts/base-packages.debian)

        # Install Brave 
        sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
        sudo apt update
        sudo apt install brave-browser
    else
        echo "A distro base is required. Options are: arch, deb."
        exit 1
    fi

}

configure_base(){
    echo "Using $DOTFILES as dotfiles config directory"
    install_packages $@
    configure_terminal
    echo "Finish with sucessful"
}


configure_base $@
