#!/bin/bash -e


exists() {
  command -v "$1" >/dev/null 2>&1
}

main() {
    if ! exists nvim; then
        echo "Neovim is not installed yet"
        exit 1
    fi

    PACKER=~/.local/share/nvim/site/pack/packer/start/packer.nvim

    if [ ! -d $PACKER ]; then
        echo "Installing packer"
        git clone --depth 1 https://github.com/wbthomason/packer.nvim $PACKER
    fi


    if [ ! -d ~/.config/nvim/venv ]; then
        echo "Creating a Python venv for Neovim"
        python3 -m venv ~/.config/nvim/venv
        ~/.config/nvim/venv/bin/pip install -U pip
        ~/.config/nvim/venv/bin/pip install pynvim
    fi

    echo "Installing language servers"
    npm config set prefix '~/.npm'

    pip3 install --user jedi-language-server

    npm i -g bash-language-server dockerfile-language-server-nodejs vim-language-server \
        yaml-language-server typescript-language-server

    nvim +PackerSync +qall

}

main
