#!/usr/bin/env bash

#/ Install tilix file configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/

. <(cat $DOTFILES_SCRIPTS/common/common)

dconf load /com/gexperts/Tilix/ < $DOTFILES/tilix/tilix.dconf
