#!/usr/bin/env bash

#/ Install tilix file configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/

set -e

help() {
     grep '^#/' < "$0" | cut -c4-
}

dconf load /com/gexperts/Tilix/ < $DOTFILES/tilix/tilix.dconf
