#!/usr/bin/env bash

#/ install asdf version manager
#/
#/ Flags:
#/   --help | -h Show help message
#/

. <(cat $DOTFILES_SCRIPTS/common/common)

ASDF_PATH=~/.asdf
ASDF_BIN=$ASDF_PATH/bin/asdf

download() {
    git clone https://github.com/asdf-vm/asdf.git $ASDF_PATH --branch v0.7.6
}

setup() {
    echo -e '\n. $HOME/.asdf/asdf.sh' >> $DOTFILES/bash/.local
    echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> $DOTFILES/bash/.local
}

download
setup

echo "asdf installed with succesfull :D"
echo "Reload bash with source ~/.bashrc and type asdf for help."
