#!/usr/bin/env bash

#/ install asdf version manager
#/
#/ Flags:
#/   --help | -h Show help message
#/

set -e

help() {
     grep '^#/' < "$0" | cut -c4-
}

ASDF_PATH=~/.asdf
ASDF_BIN=$ASDF_PATH/bin/asdf

download() {
    if [ ! -d $ASDF_PATH  ]; then
        git clone https://github.com/asdf-vm/asdf.git $ASDF_PATH --branch v0.7.6
    fi
}

setup() {
    echo -e '\n. $HOME/.asdf/asdf.sh' >> $DOTFILES/bash/.local
    echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> $DOTFILES/bash/.local
}

download
setup

echo "INFO: Finish."
