#!/usr/bin/env bash

#/ setup asdf plugins
#/
#/ Flags:
#/   --help | -h Show help message
#/

. <(cat $DOTFILES_SCRIPTS/common/common)


PYTHON_VERSION=3.7.6
GOLANG_VERSION=1.13.8
NODEJS_VERSION=12.16.0
MAVEN_VERSION=3.6.3

ASDF_PATH=~/.asdf
ASDF_BIN=$ASDF_PATH/bin/asdf

install_plugins() {
    $ASDF_BIN plugin-add python

    $ASDF_BIN plugin-add nodejs
    bash $ASDF_PATH/plugins/nodejs/bin/import-release-team-keyring

    $ASDF_BIN plugin-add golang

    $ASDF_BIN plugin-add maven
}

install_languages(){
    $ASDF_BIN install python $PYTHON_VERSION
    $ASDF_BIN global python $PYTHON_VERSION

    $ASDF_BIN install nodejs $NODEJS_VERSION
    $ASDF_BIN global nodejs $NODEJS_VERSION

    $ASDF_BIN install golang $GOLANG_VERSION
    $ASDF_BIN global golang $GOLANG_VERSION

    $ASDF_BIN install maven $MAVEN_VERSION
    $ASDF_BIN global maven $MAVEN_VERSION
}


if ! [ -x "$(command -v $ASDF_BIN)" ]; then
    echo "asdf command not found."
    echo "Try install asdf using asdf install && source ~/.bashrc"
    exit 1
fi

install_plugins
install_languages

echo "Finish."
