#!/usr/bin/env bash

#/ mod-init - Create a go mod file with basename of current path
#/
#/ Flags:
#/   --help | -h Show help message
#/

help() {
     grep '^#/' < "$0" | cut -c4-
}

CURRENT=`pwd`
BASENAME=`basename "$CURRENT"`
GITHUB_USER="msAlcantara"

go mod init github.com/$GITHUB_USER/$BASENAME
