#!/usr/bin/env bash

#/ Install polybar files configuration.
#/
#/ Flags:
#/   --help | -h Show help message
#/

. <(cat $DOTFILES_SCRIPTS/common/common)

if [ ! -d $HOME/.config/polybar ]; then
    mkdir ~/.config/polybar
fi

ln -s $DOTFILES/polybar/config $HOME/.config/polybar/config
echo "INFO: polybar config installed"

