#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done


set_variables() {
    # [module/network] variables
    export NETWORK_INTERFACE=$(ip route | grep '^default' | awk '{print $5}' | head -n1)

    # [module/battery] variables
    export BATTERY_BAT=$(ls /sys/class/power_supply/ | grep BAT)
    export BATTERY_ADAPTER=$(ls /sys/class/power_supply/ | grep -v BAT)
}

set_variables

# Launch dot bar in multiple monitors
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar dot &
  done
else
  polybar dot &
fi

echo "Polybar launched..."
